### ISSUE TITLE
TypeError: message.reactions.get is not a function

### ISSUE THREAD

**Issue by Takiyo0** [Jo3-L/discord-paginator#1]
It's working, but i get this error
```
(node:3248) UnhandledPromiseRejectionWarning: TypeError: message.reactions.get is not a function
    at ReactionCollector.<anonymous> (/Users/arya/Documents/Bot/Music Bot/ChilledChino prefix trial/node_modules/djs-pagination/index.js:62:22)
    at ReactionCollector.emit (events.js:327:22)
    at ReactionCollector.handleCollect (/Users/arya/Documents/Bot/Music Bot/ChilledChino prefix trial/node_modules/discord.js/src/structures/interfaces/Collector.js:100:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
My code is still same with the description
```
new Paginator([], { filter: (reaction, user) => user.id === message.member.user.id, timeout: 60000 }) 
	            .add(new MessageEmbed().setTitle('Page 1').setDescription('Description')) // These all need to be MessageEmbeds or RichEmbeds.
	            .add(new MessageEmbed().setTitle('Page 2').setDescription('BLABLABLA'))
	            .setEndPage(new MessageEmbed().setTitle('Done'))
	            .setTransform((embed, index, total) => embed.setFooter(`Page ${index + 1} / ${total}`)) 
	            .start(message.channel);
```

**Comment by CyclerOfLife** [comment]
Outdated, you can edit the module to the following in index.js.

```const EMOJIS = { first: '⏪', prev: '◀️', stop: '⏹️', next: '▶️', last: '⏩' };

class Paginator {
	constructor(pages = [], { filter, timeout } = { timeout: 5 * 6e4 }) {
		this.pages = Array.isArray(pages) ? pages : [];
		this.filter = typeof filter === 'function'
			? (reaction, user) => filter(reaction, user) && !user.bot && Object.values(EMOJIS).includes(reaction.emoji.name)
			: (reaction, user) => Object.values(EMOJIS).includes(reaction.emoji.name) && !user.bot;
		this.timeout = Number(timeout) || 5 * 6e4;
		this.page = 0;
	}

	add(page) {
		this.pages.push(page);
		return this;
	}

	setEndPage(page) {
		if (page) this.endPage = page;
		return this;
	}

	setTransform(fn) {
		const _pages = [];
		let i = 0;
		const ln = this.pages.length;
		for (const page of this.pages) {
			_pages.push(fn(page, i, ln));
			i++;
		}
		this.pages = _pages;
		return this;
	}

	async start(channel) {
		if (!this.pages.length) return;
		const message = await channel.send(this.pages[0]);
		for (const emoji of Object.values(EMOJIS)) await message.react(emoji);
		const collector = message.createReactionCollector(this.filter, { time: this.timeout });

		collector.on('collect', (reaction, user) => {
			switch (reaction.emoji.name) {
			case EMOJIS.first:
				message.edit(this.pages[0]);
				this.page = 0;
				break;
			case EMOJIS.prev:
				if (this.pages[this.page - 1]) message.edit(this.pages[--this.page]);
				break;
			case EMOJIS.stop:
				message.reactions.removeAll();
				collector.stop();
				break;
			case EMOJIS.next:
				if (this.pages[this.page + 1]) message.edit(this.pages[++this.page]);
				break;
			case EMOJIS.last:
				message.edit(this.pages[this.pages.length - 1]);
				this.page = this.pages.length - 1;
				break;
			}
			message.reactions.cache.get(reaction.emoji.name).users.remove(user.id);
		});

		collector.on('end', () => {
			if (this.endPage) message.edit(this.endPage);
			message.reactions.removeAll();
		});
	}
}

module.exports = Paginator;```

**Comment by TaylorIsBlue** [comment]
do npm i @awkwarddev/djspage
This is a rewrite of it ❤️ 
Nothing has changed, most common errors just fixed.

**Comment by bseales** [comment]
I have a pull request that fixes this issue.
